services:
  simplemailarchive:
    container_name: mailarchive
    image: axmeyer/simplemailarchive:latest
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /opt/mailarchive/db:/etc/maildb # sqlite database is stored here - should be on a fast drive (e.g. ssd).
      - /opt/mailarchive/accounts:/etc/mailaccounts
      - /opt/mailarchive/import:/etc/mailimport # only needed to import old e-mails from .eml files
      - /opt/mailarchive/archive:/etc/mailarchive # here all the eml files get stored. Gets large, can be on slow drives.
